package org.pwss.file_integrity_scanner.dsr.service.user_login.user;

import org.apache.tomcat.util.buf.HexUtils;
import org.pwss.file_integrity_scanner.dsr.domain.user_login.entities.user.User;
import org.pwss.file_integrity_scanner.exception.user_login.UsernameNotFoundException;
import org.springframework.security.core.userdetails.UserDetailsService;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.util.Optional;

/**
 * Service interface for managing user-related operations.
 */
public interface UserService extends UserDetailsService {

    /**
     * Creates a Hash String from an input password and splits it into 3 parts
     * (Hash,Salt,Iterations)
     *
     * @param password A clear text password
     * @return The hashed representation of the password including salt and
     *         iterations count
     * @throws NoSuchAlgorithmException If no such algorithm exists for creating
     *                                  hash
     * @throws InvalidKeySpecException  if the key specification is invalid.
     * 
     */
    default String GenerateHashWithSalt(final String password)
            throws NoSuchAlgorithmException, InvalidKeySpecException {

        final int iterations = 1000;

        byte[] salt = GenerateSalt();

        byte[] hash = CreateHash(password, salt, iterations);

        return iterations + ":"
                + HexUtils.toHexString(salt) + ":"
                + HexUtils.toHexString(hash);
    }

    /**
     * Generates a random salt.
     *
     * @return A randomly generated byte array representing the salt
     */
    private byte[] GenerateSalt() {

        SecureRandom random = null;
        try {
            random = SecureRandom.getInstance("SHA1PRNG", "SUN");
        } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
            throw new RuntimeException(e);
        }
        byte[] salt = new byte[16];

        random.nextBytes(salt);
        return salt;
    }

    /**
     * Generates a hash with salt.
     *
     * @param password A clear text password
     * @param salt     A salt that should make identical passwords into different
     *                 hashes
     * @return The hashed byte array of the password
     * @throws NoSuchAlgorithmException If no such algorithm exists for creating
     *                                  hash
     * @throws InvalidKeySpecException  if the key specification is invalid
     * 
     */
    default byte[] CreateHash(
            final String password,
            final byte[] salt,
            final int iterations)
            throws NoSuchAlgorithmException,
            InvalidKeySpecException {

        final int keyLength = 64;

        PBEKeySpec keySpec = new PBEKeySpec(password.toCharArray(),
                salt, iterations, keyLength * 8);

        SecretKeyFactory secretKeyFactory = SecretKeyFactory
                .getInstance("PBKDF2WithHmacSHA1");

        return secretKeyFactory.generateSecret(keySpec).getEncoded();

    }

    /**
     * Creates a user if validation passes.
     *
     * @param request A CreateUser request object containing user details
     * @return The created User entity
     * @throws NoSuchAlgorithmException If no such algorithm exists for creating
     *                                  hash
     * @throws InvalidKeySpecException  if the key specification is invalid
     */
    User CreateUser(org.pwss.file_integrity_scanner.dsr.domain.user_login.model.request.user_controller.CreateUser request)
            throws NoSuchAlgorithmException, InvalidKeySpecException;

    /**
     * Checks if a username already exists in the persistence layer.
     *
     * @param username A String that contains a username
     * @return True if the username exists; False otherwise
     */
    boolean CheckIfUsernameExists(String username);

    /**
     * Get a user by username.
     *
     * @param username A String that contains a username
     * @return An Optional containing the User entity, or empty if not found
     * @apiNote The entity is wrapped by an Optional class for null safety
     */
    Optional<User> GetUserByUsername(String username);

    /**
     * Checks if the repository is empty.
     *
     * @return {@code true} if the repository has no entries; {@code false}
     *         otherwise.
     */
    Boolean isEmpty();

    /**
     * Validates the input word against the stored hash.
     *
     * @param inputWord Clear text password to be validated
     * @return True if validation passes; False otherwise
     * @throws UsernameNotFoundException If user with given credentials is not found
     */
    boolean ValidatePassword(final String inputWord, String userName) throws UsernameNotFoundException;

    /**
     * Validates the http request data of a client request.
     *
     * @param request A CreateUser request object
     * @return True if validation passes; False otherwise
     */
    boolean ValidateCreateUserRequest(
            org.pwss.file_integrity_scanner.dsr.domain.user_login.model.request.user_controller.CreateUser request);

}