psql -d integrity_hash -c "DROP TABLE scan_details CASCADE;"
psql -d integrity_hash -c "DROP TABLE scans CASCADE;"
psql -d integrity_hash -c "DROP TABLE monitored_directories CASCADE;"
psql -d integrity_hash -c "DROP TABLE checksums CASCADE;"
psql -d integrity_hash -c "DROP TABLE files CASCADE;"
